# Generated by Django 4.1.3 on 2022-12-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugador',
            new_name='Jugadores',
        ),
    ]
