# Generated by Django 4.1.3 on 2022-12-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0002_rename_jugador_jugadores'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jugadores',
            new_name='Jugador',
        ),
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name_plural': 'Jugadores'},
        ),
    ]
