# Generated by Django 4.1.3 on 2022-12-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0003_rename_jugadores_jugador_alter_jugador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='apodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='apodo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estadio',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='apellido',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='equipo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(max_length=20),
        ),
    ]
