# Generated by Django 4.1.3 on 2022-12-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0005_equipo_titinternac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='titInternac',
            new_name='TitulosInternacionales',
        ),
    ]
