# Generated by Django 4.1.3 on 2022-12-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0006_rename_titinternac_equipo_titulosinternacionales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipo',
            old_name='TitulosInternacionales',
            new_name='titulosInternacionales',
        ),
    ]
