# Generated by Django 4.1.3 on 2022-12-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primerapp', '0007_rename_titulosinternacionales_equipo_titulosinternacionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fundacion',
            field=models.DateField(default='1999-10-9'),
        ),
        migrations.AddField(
            model_name='estadio',
            name='fundacion',
            field=models.DateField(default='1999-10-9'),
        ),
    ]
